print("Hello world!")
print("I'm Lizi")
print("I live in Tbilisi")
print("I am 11 yo")
print("i've got 2 sisters")
print("i've got 10 gel")
print("i'm in home")
print("I'm Chad")
print("I love mth")
print("I love GOA!")